import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

const isTablet = width >= 768;
const isSmallPhone = width < 350;

const responsiveWidth = (percentage: number): number => (width * percentage) / 100;
const responsiveHeight = (percentage: number): number => (height * percentage) / 100;
interface ResponsiveFontSizeParams {
  size: number;
}

const responsiveFontSize = (size: ResponsiveFontSizeParams['size']): number => {
  if (isSmallPhone){ return size * 0.85;}
  if (isTablet) {return size * 1.2;}
  return size;
};

export const styles = StyleSheet.create({
  highlightText: {
    fontSize: responsiveFontSize(18),
    color: '#667eea',
    fontWeight: 'bold',
    lineHeight: responsiveFontSize(28),
  },
  container: {
    justifyContent: 'center',
    flex: 1,
    backgroundColor: '#FCFCFC',
    paddingTop: Platform.OS === 'ios' ? 40 : 20,
  },
  slide: {
    width: responsiveWidth(100),
    paddingLeft: responsiveWidth(8),
    paddingRight: responsiveWidth(8),
    alignItems: 'center',
    paddingTop: responsiveHeight(5),
    paddingHorizontal: responsiveWidth(5),
  },
  illustrationImage: {
    width: responsiveWidth(85),
    height: isTablet ? 280 : responsiveHeight(25),
    marginBottom: responsiveHeight(2.5),
    resizeMode: 'contain',
    maxHeight: 250,
  },
  illustrationImageSmall: {
    width: responsiveWidth(85),
    height: isTablet ? 320 : responsiveHeight(28),
    marginBottom: responsiveHeight(2.5),
    resizeMode: 'contain',
    maxHeight: 280,
  },
  illustrationImageLarge: {
    width: responsiveWidth(95),
    height: isTablet ? 350 : responsiveHeight(30),
    marginBottom: responsiveHeight(2.5),
    resizeMode: 'contain',
    maxHeight: 320,
  },
  textContainer: {
    alignItems: 'center',
    paddingHorizontal: responsiveWidth(4),
    width: '100%',
    maxWidth: 500,
  },
  title: {
    fontSize: responsiveFontSize(isTablet ? 40 : 34),
    fontWeight: 'bold',
    marginBottom: responsiveHeight(1.5),
    color: '#000',
    textAlign: 'center',
    paddingHorizontal: responsiveWidth(2),
  },
  subtitle: {
    marginTop: responsiveHeight(2.5),
    color: '#667eea',
    fontSize: responsiveFontSize(isTablet ? 28 : 24),
    marginBottom: responsiveHeight(2.5),
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: responsiveFontSize(32),
    paddingHorizontal: responsiveWidth(2),
  },
  description1: {
    marginLeft: 0,
    fontSize: responsiveFontSize(12),
    color: 'rgb(58, 201, 226)',
    textAlign: 'center',
    lineHeight: responsiveFontSize(20),
    marginBottom: responsiveHeight(1),
    alignItems: 'center',
    fontWeight: '600',
    paddingHorizontal: responsiveWidth(3),
  },
  description: {
    marginLeft: 16,
    fontSize: responsiveFontSize(13),
    color: 'rgb(149, 149, 149)',
    textAlign: 'center',
    lineHeight: responsiveFontSize(24),
    marginBottom: responsiveHeight(1),
    alignItems: 'center',
    fontWeight: 'bold',
    paddingHorizontal: responsiveWidth(3),
  },
  description2: {
    fontSize: responsiveFontSize(isTablet ? 30 : 22),
    color: 'rgb(149, 149, 149)',
    textAlign: 'center',
    lineHeight: responsiveFontSize(32),
    marginBottom: responsiveHeight(1),
    alignItems: 'center',
    fontWeight: 'bold',
    paddingHorizontal: responsiveWidth(3),
  },
  bulletContainer: {
    margin: 0,
    width: '100%',
    alignItems: 'flex-start',
    marginTop: responsiveHeight(1.2),
    paddingHorizontal: responsiveWidth(3),
    maxWidth: 500,
  },
  bulletPoint: {
    marginLeft: responsiveWidth(2),
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: responsiveHeight(2),
    paddingRight: responsiveWidth(2),
    width: '100%',
  },
  bullet: {
    width: 8,
    height: 8,
    borderRadius: 6,
    backgroundColor: 'black',
    marginRight: 12,
    marginTop: responsiveFontSize(10),
  },
  bulletText: {
    fontSize: responsiveFontSize(16),
    fontWeight: 'bold',
    color: '#333',
    flex: 1,
    lineHeight: responsiveFontSize(24),
    textAlign: 'left',
    marginLeft: responsiveWidth(2),
  },
  roleContainer: {
    flexDirection: isTablet ? 'row' : (width < 350 ? 'column' : 'row'),
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: responsiveHeight(4),
    width: '100%',
    paddingHorizontal: responsiveWidth(2),
    flexWrap: 'wrap',
  },
  roleButton: {
    alignItems: 'center',
    backgroundColor: 'rgb(197, 223, 197)',
    padding: responsiveWidth(4),
    borderRadius: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    minWidth: isTablet ? 120 : (isSmallPhone ? 80 : 90),
    marginVertical: isSmallPhone ? 8 : 0,
    marginHorizontal: 4,
  },
  icon: {
    width: isTablet ? 110 : (isSmallPhone ? 70 : 90),
    height: isTablet ? 140 : (isSmallPhone ? 90 : 118),
    marginBottom: responsiveHeight(2),
  },
  iconPlaceholder: {
    width: isTablet ? 110 : (isSmallPhone ? 70 : 90),
    height: isTablet ? 140 : (isSmallPhone ? 90 : 118),
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: responsiveHeight(2),
  },
  iconPlaceholderText: {
    fontSize: responsiveFontSize(isTablet ? 50 : 40),
  },
  roleLabel: {
    fontSize: responsiveFontSize(isTablet ? 26 : 22),
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  bottomContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: responsiveHeight(2.5),
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 30 : 20,
    width: '100%',
  },
  dotContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: responsiveHeight(2.5),
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 8,
    backgroundColor: '#E0E0E0',
    marginHorizontal: 8,
  },
  activeDot: {
    backgroundColor: '#667eea',
    width: 10,
    height: 10,
    borderRadius: 10,
  },
  nextButton: {
    backgroundColor: '#667eea',
    paddingVertical: responsiveHeight(1.5),
    paddingHorizontal: responsiveWidth(8),
    borderRadius: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
    maxWidth: responsiveWidth(80),
    minWidth: responsiveWidth(50),
  },
  nextButtonText: {
    textAlign: 'center',
    color: 'white',
    fontSize: responsiveFontSize(18),
    fontWeight: 'bold',
    paddingVertical: 5,
  },
  point: {
    color: '#667eea',
    fontWeight: 'bold',
  },
  startContainer: {
    alignItems: 'center',
    marginTop: responsiveHeight(2.5),
    width: '100%',
    paddingHorizontal: responsiveWidth(5),
  },
  startTitle: {
    fontSize: responsiveFontSize(isTablet ? 42 : 35),
    fontWeight: 'bold',
    color: '#000',
    marginBottom: responsiveHeight(2.5),
    marginTop: responsiveHeight(-2.5),
    textAlign: 'center',
  },
  startSub: {
    fontSize: responsiveFontSize(16),
    color: '#555',
    textAlign: 'center',
    marginBottom: responsiveHeight(4),
    lineHeight: responsiveFontSize(24),
    paddingHorizontal: responsiveWidth(2),
  },
  startButton: {
    alignItems: 'center',
    marginTop: responsiveHeight(2.5),
    backgroundColor: '#667eea',
    height: responsiveHeight(7.5),
    minHeight: 50,
    width: responsiveWidth(80),
    maxWidth: 350,
    paddingVertical: responsiveHeight(1.75),
    paddingHorizontal: responsiveWidth(15),
    borderRadius: 20,
    justifyContent: 'center',
  },
  startButtonText: {
    color: 'white',
    fontSize: responsiveFontSize(15),
    fontWeight: 'bold',
    textAlign: 'center',
  },
  startButtonText1: {
    color: 'white',
    fontSize: responsiveFontSize(20),
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: responsiveWidth(5),
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: responsiveWidth(6),
    width: responsiveWidth(90),
    maxWidth: isTablet ? 500 : 400,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    maxHeight: responsiveHeight(80),
  },
  authModalContent: {
    width: responsiveWidth(95),
    maxWidth: isTablet ? 520 : 420,
    maxHeight: responsiveHeight(85),
    padding: responsiveWidth(5),
  },
  modalTitle: {
    fontSize: responsiveFontSize(isTablet ? 28 : 24),
    fontWeight: 'bold',
    color: '#333',
    marginBottom: responsiveHeight(3),
    textAlign: 'center',
  },
  modalButton: {
    height: isTablet ? 180 : (isSmallPhone ? 140 : 160),
    backgroundColor: '#F8F8F8',
    borderRadius: 15,
    padding: responsiveWidth(5),
    marginVertical: responsiveHeight(1.2),
    width: isTablet ? 220 : (isSmallPhone ? 160 : 200),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonText: {
    fontSize: responsiveFontSize(isTablet ? 34 : 30),
    fontWeight: 'bold',
    color: '#333',
    marginTop: responsiveHeight(1.5),
  },
  formContainer: {
    width: '100%',
    alignItems: 'center',
  },
  sformContainer: {
    width: '100%',
    alignItems: 'center',
    minHeight: responsiveHeight(90),
  },
  formHeading: {
    fontSize: responsiveFontSize(isTablet ? 26 : 22),
    fontWeight: 'bold',
    color: '#333',
    marginBottom: responsiveHeight(2.5),
    alignSelf: 'flex-start',
  },
  inputGroup: {
    width: '100%',
    marginBottom: responsiveHeight(1.8),
  },
  inputLabel: {
    fontSize: responsiveFontSize(14),
    marginBottom: responsiveHeight(1),
    color: '#666',
    fontWeight: '500',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    paddingHorizontal: responsiveWidth(4),
    backgroundColor: '#F8F8F8',
    minHeight: 50,
  },
  inputIcon: {
    width: 18,
    height: 18,
    marginRight: 10,
  },
  inputIconText: {
    fontSize: responsiveFontSize(18),
    marginRight: 10,
  },
  input: {
    flex: 1,
    height: 50,
    fontSize: responsiveFontSize(16),
    color: '#333',
    paddingVertical: Platform.OS === 'ios' ? 15 : 10,
  },
  forgotPassword: {
    alignSelf: 'flex-end',
    marginBottom: responsiveHeight(2.5),
  },
  forgotPasswordText: {
    color: '#667eea',
    fontSize: responsiveFontSize(14),
  },
  authButton: {
    backgroundColor: '#667eea',
    borderRadius: 12,
    paddingVertical: responsiveHeight(1.8),
    width: '100%',
    alignItems: 'center',
    marginVertical: responsiveHeight(1.2),
    minHeight: 50,
  },
  loginButton: {
    backgroundColor: '#667eea',
  },
  authButtonText: {
    color: '#FFFFFF',
    fontSize: responsiveFontSize(16),
    fontWeight: 'bold',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginVertical: responsiveHeight(2.5),
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E0E0E0',
  },
  dividerText: {
    marginHorizontal: responsiveWidth(2.5),
    color: '#999',
    fontSize: responsiveFontSize(14),
  },
  socialButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginBottom: responsiveHeight(2.5),
  },
  socialButton: {
    width: isTablet ? 60 : 50,
    height: isTablet ? 60 : 50,
    borderRadius: isTablet ? 30 : 25,
    backgroundColor: '#F8F8F8',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: responsiveWidth(2.5),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  socialIcon: {
    width: isTablet ? 28 : 24,
    height: isTablet ? 28 : 24,
  },
  socialIconText: {
    fontSize: responsiveFontSize(16),
    fontWeight: 'bold',
  },
  switchAuthMode: {
    marginTop: responsiveHeight(1.2),
    marginBottom: responsiveHeight(2.5),
  },
  switchAuthModeText: {
    color: '#667eea',
    fontSize: responsiveFontSize(14),
    textAlign: 'center',
  },
  closeButton: {
    alignSelf: 'center',
    marginBottom: responsiveHeight(1.2),
  },
  closeButtonText: {
    color: '#999',
    fontSize: responsiveFontSize(16),
  },
  closeButton1: {
    alignSelf: 'center',
    marginTop: responsiveHeight(4),
    backgroundColor: '#F8F8F8',
    paddingVertical: responsiveHeight(1.2),
    paddingHorizontal: responsiveWidth(5),
    borderRadius: 12,
  },
  closeButtonText1: {
    color: '#999',
    fontSize: responsiveFontSize(16),
  },
  termsContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginVertical: responsiveHeight(1.8),
    paddingHorizontal: responsiveWidth(1.2),
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#DDD',
    marginRight: responsiveWidth(2.5),
    marginTop: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxActive: {
    backgroundColor: '#667eea',
    borderColor: '#667eea',
  },
  checkboxInner: {
    width: 12,
    height: 12,
    backgroundColor: '#FFF',
    borderRadius: 2,
  },
  termsText: {
    fontSize: responsiveFontSize(14),
    color: '#666',
    flex: 1,
    lineHeight: responsiveFontSize(20),
  },
  termsLink: {
    color: '#667eea',
    textDecorationLine: 'underline',
  },
  iconImage: {
    width: isTablet ? 100 : (isSmallPhone ? 60 : 80),
    height: isTablet ? 100 : (isSmallPhone ? 60 : 80),
    resizeMode: 'contain',
  },
  formContainer1: {
    marginTop: responsiveHeight(15),
  },
  deviceCodeText: {
    marginTop: responsiveHeight(1.8),
    fontSize: responsiveFontSize(isTablet ? 32 : 28),
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'rgb(76, 175, 140)',
  },
});
