import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 25,
    width: "90%",
    maxWidth: 400,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  authModalContent: {
    width: "95%",
    maxWidth: 420,
    maxHeight: "100%",
    padding: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 25,
    textAlign: "center",
  },
  modalButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F8F8",
    borderRadius: 15,
    padding: 20,
    marginVertical: 10,
    width: 250,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  modalButtonText: {
    marginTop: -20,
    marginBottom: -150,
    fontSize: 18,
    fontWeight: "600",
    marginLeft: -63,
    color: "#333",
  },
  icon: {
    marginTop: -15,
    marginLeft: 65,
    width: 80,
    height: 118,
    marginBottom: 16,
  },
  qrContainer: {
    width: "100%",
    alignItems: "center",
    padding: 15,
  },
  qrTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 10,
  },
  qrSubtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    marginBottom: 25,
  },
  qrCodeBox: {
    backgroundColor: "#FFF",
    padding: 15,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    width: 230,
    height: 230,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  qrLoadingText: {
    fontSize: 16,
    color: "#999",
  },
  closeQrButton: {
    backgroundColor: "#4CAF50",
    marginTop: 20,
  },
  qrDataDisplay: {
    width: "100%",
    backgroundColor: "#F5F5F5",
    padding: 10,
    borderRadius: 8,
    marginTop: 15,
  },
  qrDataTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#555",
    marginBottom: 5,
  },
  qrDataContent: {
    fontSize: 12,
    color: "#777",
  },
  inputGroup: {
    width: "100%",
    marginBottom: 15,
  },
  inputLabel: {
    fontSize: 14,
    marginBottom: 8,
    color: "#666",
    fontWeight: "500",
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 12,
    paddingHorizontal: 15,
    backgroundColor: "#F8F8F8",
  },
  inputIcon: {
    width: 18,
    height: 18,
    marginRight: 10,
  },
  input: {
    flex: 1,
    height: 50,
    fontSize: 16,
    color: "#333",
  },
  authButton: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    color: "#fff",
    backgroundColor: " #4CAF50",
    borderRadius: 12,
    paddingVertical: 15,
    width: "100%",
    alignItems: "center",
    marginVertical: 10,
  },
})
