import { StyleSheet, Dimensions } from "react-native"

export const styles = StyleSheet.create({
  highlightText: {
    fontSize: 18,
    color: "#4CAF50", 
    fontWeight: "bold",
    lineHeight: 24,
  },
  container: {
    flex: 1,
    backgroundColor: "#FCFCFC",
    paddingTop: 20, // 음수값(-20)에서 수정
  },
  slide: {
    alignItems: "center",
    paddingTop: 40,
    paddingHorizontal: 20,
    width: Dimensions.get("window").width,
    flex: 1,
  },
  illustrationImage: {
    width: 200,
    height: 210,
    marginBottom: 24,
    resizeMode: "contain",
  },
  illustrationImageSmall: {
    width: "70%",
    height: 240,
    marginBottom: 24,
    resizeMode: "contain",
  },
  illustrationImageLarge: {
    marginTop: -140,
    width: "100%",
    height: 250,
    marginBottom: 24,
    resizeMode: "contain",

  },
  textContainer: {
    marginHorizontal: 16,
    alignItems: "center",
    paddingHorizontal: 15,
    width: "100%",
  },
  title: {
    fontSize: 34,
    fontWeight: "bold",
    marginBottom: 16,
    color: "#000",
    textAlign: "center",
  },
  subtitle: {
    color: "#4CAF50",
    fontSize: 20,
    marginBottom: 20,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 28,
  },
  description1: {
    fontSize: 14, // 10에서 조정
    color: "rgb(58, 201, 226)",
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 16, // -27에서 수정
    fontWeight: "600",
  },
  description: {
    marginLeft: 20,
    fontSize: 16,
    color: "rgb(149, 149, 149)",
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 16,
    fontWeight: "600",
  },
  bulletContainer: {
    width: "100%",
    alignItems: "flex-start",
    marginTop: 16,
    paddingHorizontal: 16,
  },
  bulletPoint: {
    marginTop: -10,
    marginLeft:20,
    flexDirection: "row",
    alignItems: "flex-start", 
    marginBottom: 16,
    paddingRight: 10,
  },
  bullet: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#000",
    marginRight: 12,
    marginTop: 8, 
  },
  bulletText: {
    fontSize: 15,
    color: "#333",
    flex: 1,
    lineHeight: 24,
    textAlign: "left",
  },
  bottomContainer: {
    flexDirection: "column",
    alignItems: "center",
    paddingVertical: 20,
    position: "absolute",
    bottom: 30,
    width: "100%",
  },
  dotContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 30,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#E0E0E0",
    marginHorizontal: 6,
  },
  activeDot: {
    backgroundColor: "#4CAF50",
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  nextButton: {
    backgroundColor: "rgb(108, 187, 111)",
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 30,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  nextButtonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    width: 220,
  },
  point: {
    color: "rgb(108, 187, 111)",
    fontWeight: "bold",
  },
  startContainer: {
    alignItems: "center",
    marginTop: 20,
    width: "100%",
    paddingHorizontal: 20,
  },
  startTitle: {
    marginTop: -20,
    fontSize: 34,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 10,
    textAlign: "center",
  },
  startSub: {
    fontSize: 16,
    color: "#555",
    textAlign: "center",
    marginBottom: 30,
    lineHeight: 24,
    paddingHorizontal: 10,
  },
  startButton: {
    alignItems: "center",
    justifyContent: "center", // 버튼 내 컨텐츠 정렬
    backgroundColor: "rgb(108, 187, 111)",
    height: 60,
    width: 320,
    borderRadius: 20,
  },
  startButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  startButtonText1: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
})